name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site 
      run: |
        docker run \
        -v ${{ github.workspace }}:/documents/  \
        asciidoctor/docker-asciidoctor:latest /bin/bash -c "asciidoctor README.adoc"
